### ISSUE TITLE
Patches for > 5.3.x

### ISSUE THREAD

**Issue by thopiekar** [martinkarlweber/rcraid-patches#14]
You might want to apply it to your patchset.

However, never got 5.1 or 5.2 working.

https://github.com/thopiekar/rcraid-dkms/

**Comment by misiektw** [comment]
Same here. Just tried upgrade 4.19 to 5.4 because new virtio features. First it was Makefile. Got around it:

`  $(MAKE) -C $(KDIR) SUBDIRS=$(PWD) modules   `
 to
`  $(MAKE) -C $(KDIR) M=$(PWD) SUBDIRS=$(PWD) modules   `

However then I'm getting something similar like in 4.19 before Martin patches:


`CC [M]  /src/rcraid-17.2.1/rc_init.o
/src/rcraid-17.2.1/rc_init.c:335:29: error: initialization of ‘int (*)(struct scsi_device *, unsigned int,  void *)’ from incompatible pointer type ‘int (*)(struct scsi_device *, int,  void *)’ [-Werror=incompatible-pointer-types]
  335 |  .ioctl =                   rc_ioctl,
      |                             ^~~~~~~~

/src/rcraid-17.2.1/rc_init.c:335:29: note: (near initialization for ‘driver_template.ioctl’)
`

**Comment by misiektw** [comment]
NVM, I found patch for incompatible pointer in your repo. Just assumed wrong about code version, because your Makefile doesn't have fix I need in Arch. Sorry.

**Comment by dylanreich** [comment]
@misiektw Did you find a fix for > 5.3? Or do you plan on making one @martinkarlweber? Great work here. Would love to run Ubuntu 20 with this :)

**Comment by thopiekar** [comment]
@dylanreich Check my PPA. Works perfectly fine with SATA drives. Have no experience with NVMe.

**Comment by misiektw** [comment]
@dylanreich Just like Thomas said, it runs just fine with 5.4.44 in my case... Been using it for months with 5.4 series without major issues. Manjaro in my case.

**Comment by dylanreich** [comment]
Sorry for the delay. I believe it's because I have a TRX40 board.
